
export const websites = [
  {
    "name": "BlablaBook",
    "title": "O'Clock School Apotheosis Project:",
    "text": "This is an online personal library management platform created by a fictitious association of reading enthusiasts.",
    "tech": "Front: React/SASS and nginx server, Back: NodeJS/Express, Axios API, Sequelize, PostgreSQL",
    "img": "blablabook.jpeg",
    "url": "https://blablabook.init17.com/",
    "font": "Satisfy",
    "fontSize": "3rem",
    "color": "",
  }, 
  {
    "name": "O'Coffee",
    "title": "O'Clock School MVC Project:",
    "text": "The Pepper Brothers are retailers of premium coffee and coffee-related products.",
    "tech": "MCD/MLD, Creation of the wireframe, HTML/CSS, VanillaJS, NodeJS/Express, PostgreSQL and nginx server self-managed on VPS",
    "img": "pexels-ifreestock-585753.jpg",
    "url": "http://ocoffee.init17.com/",
    "font": "Montserrat",
    "fontSize": "4rem",
    "color": "",
  }, 
  {
    "name": "Gaming Campus",
    "title": "Web integration exercise:",
    "text": "From a wireframe, creation of the homepage of a gaming school",
    "tech": "HTML/CSS on GitHub Pages",
    "img": "bg-gamingcampus.jpg",
    "url": "  https://init-dev17.github.io/CSS-TP5-GamingCampus/",
    "font": "Montserrat, sans-serif",
    "fontSize": "3rem",
    "color": "#ede4d0",
  },
  {
    "name": "Mountain vacations",
    "title": "Web integration exercise:",
    "text": "From a wireframe, creation of a blog website to book trips.",
    "tech": "HTML/SASS on GitHub Pages",
    "img": "bg-montagne.jpg",
    "url": "https://init-dev17.github.io/SASS-TP1-Montagne/",
    "font": "Merriweather",
    "fontSize": "2.7rem",
    "color": "",
  },
  {
    "name": "READY PLAY EARTH2",
    "title": "",
    "text": "Earth2 build a 1:1 scale virtual Earth that will not only allow you to play, explore and experience.",
    "tech": "",
    "img": "pexels-photo-355935.jpeg",
    "url": "https://init-dev17.github.io/101---data-Earth2",
    "font": "Audiowide",
    "fontSize": "1.8rem",
    "color": "",
  }, 
  // {
  //   "name": "Eisenhower matrix",
  //   "title": "",
  //   "text": "The Eisenhower Matrix is a productivity, prioritization, and time-management framework designed to help you prioritize a list of tasks or agenda items.",
  //   "tech": "",
  //   "img": "pexels-shvetsa-4586899.jpg",
  //   "url": "https://init-dev17.github.io/",
  //   "font": "IndieFlower",
  //   "fontSize": "3.1rem",
  //   "color": "",
  // },
  // {
  //   "name": "Freedom",
  //   "text": "Do you want to travel ?",
  //   "img": "cta.jpg",
  //   "url": "https://www.google.com",
  //   "font": "",
  //   "fontSize": "",
  //   "color": "",
  // },
  // {
  //   "name": "Road trip",
  //   "text": "Come and discover Japan!",
  //   "img": "japan-thomas.jpg",
  //   "url": "https://www.japan.com",
  //   "font": "SawarabiMincho",
  //   "fontSize": "2.3rem",
  //   "color": "",
  // },
  // {
  //   "name": "Egypt",
  //   "text": "",
  //   "img": "Egypt.jpg",
  //   "url": "https://www.google.com",
  //   "font": "",
  //   "fontSize": "",
  //   "color": "",
  // },
  
];
